//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelRuler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string AnnotationColor {
            get {
                return ((string)(this["AnnotationColor"]));
            }
            set {
                this["AnnotationColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseToTray {
            get {
                return ((bool)(this["CloseToTray"]));
            }
            set {
                this["CloseToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DayNightMode {
            get {
                return ((int)(this["DayNightMode"]));
            }
            set {
                this["DayNightMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OnLaunchAction {
            get {
                return ((int)(this["OnLaunchAction"]));
            }
            set {
                this["OnLaunchAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GlobalShortcutsEnabled {
            get {
                return ((bool)(this["GlobalShortcutsEnabled"]));
            }
            set {
                this["GlobalShortcutsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutFullscreenKey {
            get {
                return ((int)(this["GlobalShortcutFullscreenKey"]));
            }
            set {
                this["GlobalShortcutFullscreenKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutFullscreenModifiers {
            get {
                return ((int)(this["GlobalShortcutFullscreenModifiers"]));
            }
            set {
                this["GlobalShortcutFullscreenModifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartAtWindowsStartup {
            get {
                return ((bool)(this["StartAtWindowsStartup"]));
            }
            set {
                this["StartAtWindowsStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LaunchStartupAction {
            get {
                return ((int)(this["LaunchStartupAction"]));
            }
            set {
                this["LaunchStartupAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultTool {
            get {
                return ((int)(this["DefaultTool"]));
            }
            set {
                this["DefaultTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutWindowKey {
            get {
                return ((int)(this["GlobalShortcutWindowKey"]));
            }
            set {
                this["GlobalShortcutWindowKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutWindowModifiers {
            get {
                return ((int)(this["GlobalShortcutWindowModifiers"]));
            }
            set {
                this["GlobalShortcutWindowModifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutRegionKey {
            get {
                return ((int)(this["GlobalShortcutRegionKey"]));
            }
            set {
                this["GlobalShortcutRegionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutRegionModifiers {
            get {
                return ((int)(this["GlobalShortcutRegionModifiers"]));
            }
            set {
                this["GlobalShortcutRegionModifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutQuickColorKey {
            get {
                return ((int)(this["GlobalShortcutQuickColorKey"]));
            }
            set {
                this["GlobalShortcutQuickColorKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutQuickColorModifiers {
            get {
                return ((int)(this["GlobalShortcutQuickColorModifiers"]));
            }
            set {
                this["GlobalShortcutQuickColorModifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutQuickMeasureKey {
            get {
                return ((int)(this["GlobalShortcutQuickMeasureKey"]));
            }
            set {
                this["GlobalShortcutQuickMeasureKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlobalShortcutQuickMeasureModifiers {
            get {
                return ((int)(this["GlobalShortcutQuickMeasureModifiers"]));
            }
            set {
                this["GlobalShortcutQuickMeasureModifiers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultPathInfo {
            get {
                return ((string)(this["DefaultPathInfo"]));
            }
            set {
                this["DefaultPathInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalPathInfos {
            get {
                return ((string)(this["AdditionalPathInfos"]));
            }
            set {
                this["AdditionalPathInfos"] = value;
            }
        }
    }
}
